[package]
name = "graph_builder"
version = "0.3.2"
authors = ["Kelvin Samuel <kelvin@kks110.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"
chrono = "0.4"
